# version: '3'
# services:
#   web:
#     image: cuznerdexter/cuzdex-hub:latest
#     deploy:
#       replicas: 1
#       resources:
#         limits:
#           cpus: "0.1"
#           memory: 50M
#       restart_policy:
#         condition: on-failure
#     ports:
#       - "3000:3000"
#     networks:
#       - webnet
# networks:
#   webnet:
