version: '3'
services:
  web:
    image: cuznerdexter/cuzdex-hub:second
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
