version: 2.0
jobs:
  build:
    docker:
      - image: cuznerdexter/cuzdex-hub:latest
    working_directory: /usr/src/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7a:f2:fa:72:60:2c:3c:7e:56:2a:8f:1f:d2:12:8d:3e"
            - "8a:16:bb:e8:ed:11:ee:96:4f:bd:ad:03:e8:d0:8c:42"
            - "26:95:25:51:5c:8c:ba:48:97:50:a9:8a:d7:56:ba:62"
            
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose 
      - setup_remote_docker
      - run:
          name: Deployer cuzdex-hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "node-test-dev" ]; then
              ssh $DEPLOY_USER@$DEPLOY_HOST
              docker login -u $DOCKER_USER -p DOCKER_PASS 
              docker run -d cuznerdexter/cuzdex-hub:latest
            fi
